# Generated by Django 4.0.6 on 2022-07-23 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='character',
        ),
        migrations.AddField(
            model_name='photo',
            name='tamagotchi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.tamagotchi'),
            preserve_default=False,
        ),
    ]
