# Generated by Django 4.0.6 on 2022-07-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamagotchi',
            name='pet_type',
            field=models.CharField(choices=[('A', 'Kuchipatchi'), ('B', 'Memetchi'), ('C', 'Momotchi'), ('D', 'Mametchi')], default=('A', 'Kuchipatchi'), max_length=100),
        ),
    ]
